// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKjhpvomWPxDRqLNRu-u6Itilrw38K6A',
    appId: '1:993215867881:android:2030d353cbf8c52b4cb978',
    messagingSenderId: '993215867881',
    projectId: 'farmers-hub-9b6c3',
    storageBucket: 'farmers-hub-9b6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gSJ4xZ0J7NqfIQOl6ojjHrP7-2XMSWs',
    appId: '1:993215867881:ios:8d2aed9b99f84d764cb978',
    messagingSenderId: '993215867881',
    projectId: 'farmers-hub-9b6c3',
    storageBucket: 'farmers-hub-9b6c3.firebasestorage.app',
    androidClientId: '993215867881-eb19qo72fm1qtapltemseh29t2meja24.apps.googleusercontent.com',
    iosClientId: '993215867881-582afiboqi4sqjj91da33v0pl22kp231.apps.googleusercontent.com',
    iosBundleId: 'com.farmers.hub.farmersHub',
  );

}